# Generated by Django 3.2.13 on 2023-01-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='basket_histore',
            new_name='basket_history',
        ),
    ]
