# Generated by Django 4.1.6 on 2023-02-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_basket_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
